# Generated by Django 3.0.5 on 2020-05-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
